#
# This file contains configuration flags to customize your site
#
---
layout: post
# Name of your site (displayed in the header)
name: Claire's Blog
description: 
---

url: "http://yl3296.github.io" 

background-image: url('https://cloud.githubusercontent.com/assets/10662777/6995166/cad7970a-db04-11e4-9b53-b1976f88b15e.jpg
')

